function [prefix,magnitude] = SIprefix(num)
%UNTITLED13 Summary of this function goes here
%   Detailed explanation goes here
tbl = {...
    30,'Q';...
    27,'R';...
    24,'Y';...
    21,'Z';...
    18,'E';...
    15,'P';...
    12,'T';...
    9,'G';...
    6,'M';...
    3,'k';...
    0,'';...
    -3,'m';...
    -6,[char(956)];... % micro sign
    -9,'n';...
    -12,'p';...
    -15,'f';...
    -18,'a';
    -21,'z';...
    -24,'y';...
    -27,'r';...
    -30,'q'...
    };
if(num < 0)
    [prefix,magnitude] = SIprefix(-num);
elseif(num == 0)
    error('no SI prefix (num is 0)');
else
    idx = 11-floor(floor(log10(num))/3);
    prefix = tbl{idx,2};
    magnitude = 10^tbl{idx,1};
end